# Copy required directories (Main.py sits at same level as src) - TODO: This needs some work and testing

COPY docs {{APP_DIR}}/docs
COPY {{APP_DIR}} {{APP_DIR}}/{{APP_DIR}}
COPY data {{APP_DIR}}/data
COPY settings.toml {{APP_DIR}}/

# Set the working directory

WORKDIR /{{APP_DIR}}

# Run {{APP_DIR}}

ENTRYPOINT ["streamlit", "run", "{{STREAMLIT_RUN_PY}}", "--server.port={{SERVER_PORT}}", "--server.address=0.0.0.0"]

# See https://discuss.streamlit.io/t/deploying-streamlit-on-gcp-cloud-run-problem-when-using-new-multipage-{{APP_DIR}}-feature/26316/3